### PR TITLE
Added elevation and speed data. Also some more additional documentation ...

### PR DESCRIPTION
**Pull request by rgeyer**
...and config example'y goodness

### CODE REVIEW

**Comment by kimeberz** [comment]
This is awesome, Ryan!! I'll check it out and see how it looks after work, then merge it in!! :beer:

**Comment by rgeyer** [comment]
Sweet! You'll probably want to "prettify" the additional data, I just copied the classes you had for count and miles, and it gets a bit ugly in the presentation. A UX dude, I am not!

**Comment by kimeberz** [comment]
This is great! 

image

I'm tempted to apply some math to convert the elevation to feet... what do you think?

I'm also going to think about how to style this additional data, It seems like we have too much in the card now. 

Thank you for contributing! :+1: :dancer:

**Comment by rgeyer** [comment]
Christ you're a fast runner!

Whoa..

Anyhow, yeah, I think the formatting isn't great, I didn't spend a lot of
time on that. As for the units, the user stats (or maybe profile?) API call
includes the users preference for units (feet or meters). I thought about
using that to determine the right way to display it, but went with meters
because it's the "accepted" standard for measuring elevation in cycling.
It's more of a style thing.

I might be persuaded to hack on it a bit more and add the ability to
inherit the users Strava preference for units, or maybe even make it an
option in the app?

As for presentation/formatting, I'm not sure the best way to improve that
frankly. I just threw the data out there in hopes that you could tweak that
better :)

**Comment by kimeberz** [comment]
LOL, thanks! I've been running too much since I moved up here... I miss my bike! :cry: 

Ok, I think it makes sense to keep the units the same then, I just wanted to make sure that meters was the standard you were going for. I had to convert the meters to miles for distance - which I think still makes sense. 

I'll work on the presentation... I'm thinking of reformatting the cards anyways, and now that we have more data it makes sense to do so! :grinning:

**Comment by kimeberz** [comment]
I finally got your PR merged! Thanks for contributing, and sorry for taking so long! :beers: 

http://fitnezz.cfapps.io/

**Comment by rgeyer** [comment]
Woot! No worries. Glad I could contribute :)

**Pull request merged**
